### ISSUE TITLE
autoconf v2.68

### ISSUE THREAD

**Issue by psyhtest** [Meinersbur/pencilcc#2]
On an Ubuntu 12.04 platform, `autoconf` v2.69 is unavailable but `autoconf` v2.68 seems to work. You may want to update the following `configure.ac` files:

```
pencilcc/configure.ac
pencilcc/prl/configure.ac
pencilcc/pencil-headers/configure.ac
```

The only problem I encountered was that the following `m4` directories had to be manually created:

```
$ mkdir pencilcc/prl/m4
$ mkdir pencilcc/pencil-headers/m4
```

It could be or could be not related to `autoconf` v2.68.

**Comment by Meinersbur** [comment]
2015-10-13 13:35 GMT+02:00 Anton Lokhmotov notifications@github.com:

> On an Ubuntu 12.04 platform, autoconf v2.69 is unavailable but autoconf
> v2.68 seems to work.
> 
> I have no means of testing older/multiple autoconf versions. I just use the
> one installed on my system.
> 
> You may want to update the following configure.ac files:
> 
> pencilcc/configure.ac
> pencilcc/prl/configure.ac
> pencilcc/pencil-headers/configure.ac
> 
> The only problem I encountered was that the following m4 directories had
> to be manually created:
> 
> $ mkdir pencilcc/prl/m4
> $ mkdir pencilcc/pencil-headers/m4
> 
> It could be or could be not related to autoconf v2.68.
> 
> I never encountered this. Does 'make distcheck' work out of the box with
> autoconf 2.68 ? One cannot store empty directories in git, making this a
> permanent problem. It might just because 'git reset --hard' does not delete
> empty directories, but I don't know who created the folders in the first
> place. If it is indeed an issue of the autoconf version, I'd keep it at
> 2.69. I don't expect users to create directories on their own.

Michael

## 

Tardyzentrismus verboten!

**Comment by psyhtest** [comment]
What's interesting is that on another platform, with `automake` v1.15, I got exactly two error messages:

```
aclocal-1.15: warning: couldn't open directory 'm4': No such file or directory
```

which are presumably (but necessarily) for the directories `pencilcc/prl/m4` and `pencilcc/pencil-headers/m4` that I had to create on the older platform.

**Comment by Meinersbur** [comment]
For a fresh checkout, I also get this warning. It might be related with the
line

ACLOCAL_AMFLAGS = -I m4

libtool puts files into the m4 directory, so it is needed. It is just that
libtool after aclocal. Seems to be one of the plenty flaws of the autotools.

Is this a pressing issue? It's just a warning, and even doesn't appear
anymore when re-running autogen.sh. The only way I knew how to fix this is
to put a dummy file into the m4 directory so they directory exists within
git.

If you know a better solution, feel free to sugest one.

Michael

2015-10-15 15:40 GMT+02:00 Anton Lokhmotov notifications@github.com:

> What's interesting is that on another platform, with automake v1.15, I
> got exactly two error messages:
> 
> aclocal-1.15: warning: couldn't open directory 'm4': No such file or directory
> 
> which are presumably (but necessarily) for the directories pencilcc/prl/m4
> and pencilcc/pencil-headers/m4 that I had to create on the older platform.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Meinersbur/pencilcc/issues/2#issuecomment-148390081.

## 

Tardyzentrismus verboten!

**Comment by Meinersbur** [comment]
For a fresh checkout, I also get this warning. It might be related with the
line

ACLOCAL_AMFLAGS = -I m4

There is nothing in the m4 directory, so in princple it is useless. But I
get another warning if removed:

It this a pressing issue? It's just a warning, and even doesn't appear
anymore when re-running autogen.sh

Michael

2015-10-15 15:40 GMT+02:00 Anton Lokhmotov notifications@github.com:

> What's interesting is that on another platform, with automake v1.15, I
> got exactly two error messages:
> 
> aclocal-1.15: warning: couldn't open directory 'm4': No such file or directory
> 
> which are presumably (but necessarily) for the directories pencilcc/prl/m4
> and pencilcc/pencil-headers/m4 that I had to create on the older platform.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Meinersbur/pencilcc/issues/2#issuecomment-148390081.

## 

Tardyzentrismus verboten!

**Comment by Meinersbur** [comment]
I am closing this issue. Maybe there is an autotools expert out there who knows how it is supposed how this should be handled. At the moment creating empty directories in git to suppress this warning would create more issues than just that warning.
