### ISSUE TITLE
Update documentation for dependencies 

### ISSUE THREAD

**Issue by psyhtest** [Meinersbur/pencilcc#3]
While installing `pencilcc` on a couple of development board, I discovered the following undocumented dependencies:
- BSD editline and history libraries: `libedit-dev` (Ubuntu 12.04: 2.11-20080614-3ubuntu2; Ubuntu 14.04: 3.1-20130712-2 )
- zlib compression library: `zlib1g-dev` (Ubuntu 12.04: 1.2.3.4.dfsg-3ubuntu4; Ubuntu 14.04: 1.2.8.dfsg-1ubuntu)

The following versions seems to work:
- `libgmp-dev`: 5.1.3
- `libtool`: 2.4.2
- `pkg-config`: 0.26
- `autoconf`: 2.68, 2.69
- `libclang-3.?-dev`, `llvm-3.?-dev`: 3.3, 3.4, 3.5, 3.6

A note on installing Clang/LLVM. To avoid passing special flags to `configure`, make `llvm-config` discoverable e.g.:

```
$ sudo apt-get install libclang-3.6-dev
$ sudo apt-get install llvm-3.6-dev
$ sudo apt-get install llvm-3.6-tools
$ sudo ln -s /usr/bin/llvm-config-3.6 /usr/bin/llvm-config
```

**Comment by Meinersbur** [comment]
2015-10-13 13:53 GMT+02:00 Anton Lokhmotov notifications@github.com:

> While installing pencilcc on a couple of development board, I discovered
> the following undocumented dependencies:
> - BSD editline and history libraries: libedit-dev (Ubuntu 12.04:
>   2.11-20080614-3ubuntu2; Ubuntu 14.04: 3.1-20130712-2 )
> - zlib compression library: zlib1g-dev (Ubuntu 12.04:
>   1.2.3.4.dfsg-3ubuntu4; Ubuntu 14.04: 1.2.8.dfsg-1ubuntu)
> 
> I think these are indirect requirements through clang/llvm. There are
> probably a lot more and I don't think it makes sense to list them all.
> 
> The following versions seems to work:
> - libgmp-dev: 5.1.3
> - libtool: 2.4.2
> - pkg-config: 0.26
> - autoconf: 2.68, 2.69
> - libclang-3.?-dev, llvm-3.?-dev: 3.3, 3.4, 3.5, 3.6
> 
> Thanks for reporting.
> 
> A note on installing Clang/LLVM. To avoid passing special flags to
> configure, make llvm-config discoverable e.g.:
> 
> $ sudo apt-get install libclang-3.6-dev
> $ sudo apt-get install llvm-3.6-dev
> $ sudo apt-get install llvm-3.6-tools
> $ sudo ln -s /usr/bin/llvm-config-3.6 /usr/bin/llvm-config
> 
> This is Debian-specific which changes the prefix directory layout. I might
> write a guide for installing on the most recent Ubuntu (apt-get install
> ..., etc.).

Michael

## 

Tardyzentrismus verboten!

**Comment by psyhtest** [comment]
> I think these are indirect requirements through clang/llvm. There are
> probably a lot more and I don't think it makes sense to list them all.

Sure. It could be `pet` that needs them. But these made me stop "configure" or "make", think, fix and restart on a couple of fairly bare boards. Hence I believe installation should work on most platforms, once those dependencies are satisfied.

> I might write a guide for installing on the most recent Ubuntu (apt-get install ..., etc.).
> This would be handy. It's easier to copy-and-paste a single (however long) command line, then iteratively finding which packages need to be installed (see above).

With Collective Knowledge, we actually have a wiki per tool where people can gradually add versions of software they tested the tool with. I might migrate this information there.

**Comment by Meinersbur** [comment]
2015-10-13 15:50 GMT+02:00 Anton Lokhmotov notifications@github.com:

> I think these are indirect requirements through clang/llvm. There are
> probably a lot more and I don't think it makes sense to list them all.
> Sure. It could be pet that needs them. But these made me stop "configure"
> or "make", think, fix and restart on a couple of fairly bare boards. Hence
> I believe installation should work on most platforms, once those
> dependencies are satisfied.
> 
> You may look up LLVM/Clang's dependencies on their internet page. Package
> maintainers should probably have added dependency on them when installing
> llvm-dev.

With Collective Knowledge, we actually have a wiki per tool where people

> can gradually add versions of software they tested the tool with. I might
> migrate this information there.
> 
> How would a closed external wiki I don't have access to concern me?

Michael

## 

Tardyzentrismus verboten!

**Comment by psyhtest** [comment]
> How would a closed external wiki I don't have access to concern me?

External - true, but not closed - quite the contrary! Once I manage, with your help, to describe `pencilcc` in CK, I will share the description on GitHub for anybody to see.

For example, for [SLAMBench](http://apt.cs.manchester.ac.uk/projects/PAMELA/tools/SLAMBench/) described in CK, I can trivially open a wiki page:

```
anton@localhost / $ ck webhelp program:slambench-1.1-opencl
Opening web page https://github.com/ctuning/ck/wiki/ckb_b0ac08fe1d3c2615_6a7145744fa93c7e ...
```

(You can simply open the link in your browser.)

**Comment by psyhtest** [comment]
> You may look up LLVM/Clang's dependencies on their internet page. Package maintainers
>  should probably have added dependency on them when installing llvm-dev.

Is it possible that LLVM has nothing to do with it and it's a proper dependence of `pencilcc` via `pet`, `isl` or `ppcg`?

**Comment by Meinersbur** [comment]
2015-10-14 12:25 GMT+02:00 Anton Lokhmotov notifications@github.com:

> You may look up LLVM/Clang's dependencies on their internet page. Package maintainers
> should probably have added dependency on them when installing llvm-dev.
> 
> Is it possible that LLVM has nothing to do with it and it's a proper dependence of pencilcc via pet, isl or ppcg?

$ llvm-config --system-libs
-lz -lpthread -lffi -ledit -ltinfo -ldl -lm

Neither "zlib", "libedit", "libz", "-lz" nor "-ledit" appear in
pencilcc or any of its subprojects in a context related to linking or
packages.

Michael

## 

Tardyzentrismus verboten!

**Comment by psyhtest** [comment]
Fair enough. Closing this issue.
