### ISSUE TITLE
Missing '$' for a variable replacement

### ISSUE THREAD

**Issue by laorans** [Meinersbur/pencilcc#8]
# Probably missing '$' for a variable replacement in pencilcc.py.in

Install script misses also the installation of the ocl_utility files.

Version:
commit e92daa56b8f63e723740a2ef3947cf797a71b3b4

The patch (wrapper only, for the second one, ask or give write access to github):

``` patch
diff --git a/pencilcc.py.in b/pencilcc.py.in
index 0ee056a..e9ccf91 100755
--- a/pencilcc.py.in
+++ b/pencilcc.py.in
@@ -27,7 +27,7 @@ includedir='''@includedir@'''.replace('''${prefix}''', prefix)
 bindir='''@bindir@'''.replace('''${exec_prefix}''', exec_prefix)
 libdir='''@libdir@'''.replace('''${exec_prefix}''', exec_prefix)
 datarootdir='''@datarootdir@'''.replace('''${prefix}''', prefix)
-datadir='''@datadir@'''.replace('''{datarootdir}''',datarootdir).replace('''${prefix}''', prefix)
+datadir='''@datadir@'''.replace('''${datarootdir}''',datarootdir).replace('''${prefix}''', prefix)

 PPCG_BUILDDIR='''@PPCG_BUILDDIR@'''
 PPCG_SRCDIR='''@PPCG_SRCDIR@'''
```

**Comment by Meinersbur** [comment]
Fixed in e2e2865. Thanks for reporting the issue. I'd like very much like to hear about the second occurrence.

ocl_utilities{.c|.h} are pre-PRL files and are not supported. .c files are not supposed to be installed.

AFAIK one cannot grant write access to personal profile repositories on github.
